import type { Metadata } from "next";
import "./globals.css";
import Link from "next/dist/client/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-red-500 gap-4 p-4 text-white flex justify-center xl:text-2xl">
          <Link href="/">Home</Link> | <Link href="/about">About</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
